name: CI to Docker Hub
 
on:
 push:
   branch:
     main

jobs:
 
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         lfs: true

     - name: Publish to Registry
       uses: elgohr/Publish-Docker-Github-Action@master
       with:
         name: rmurphy599/cutepredictor:latest
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         workdir: CutePredictionAPI